/*
 * This source file was generated by the Gradle 'init' task
 */
package day2;

import static java.lang.System.out;

public class Car {
    int maxSpeed= 100;
    int minSpeed= 0;

    double weight= 4079;

    boolean isTheCarOn= false;
    char condition= 'D';
    String nameOfCar= "Betty";

    double maxFuel = 16;
    double currentFuel = 8;
    double mpg= 26.4;

    int numberOfPeopleInCar = 1;

    public Car(int customMaxSpeed, double customWeight, double customMaxFuel) {
        maxSpeed= customMaxSpeed;
        weight= customWeight;
        maxFuel= customMaxFuel;
    }

    public void printVariables() {
        out.println("   max speed: "+ maxSpeed);
        out.println("   min speed: "+ minSpeed);
        out.println("   weight: "+ weight);
        out.println("   is the car on: " +isTheCarOn);
        out.println("   condition: " +condition);
        out.println("   name of car: " +nameOfCar);
        out.println("   max fuel: "+maxFuel);
        out.println("   current fuel: "+currentFuel);
        out.println("   mpg: "+mpg);
        out.println("   number of people in car: "+numberOfPeopleInCar);
    }

    public void washTheCar() {
        condition='A';
    }

    public void getIn() {
        numberOfPeopleInCar++;
    }

    public void getOut() {
        numberOfPeopleInCar--;
    }

    public double howManyMilesTillOutOfGas() {
        return currentFuel * mpg;
    }

    public double maxMilesPerFillUp() {
        return maxFuel * mpg;
    }

    public static void main(String[] args) {
        Car birthdayCar = new Car(500,5000.43,30);
        System.out.println("\n birthday car v1:");
        birthdayCar.printVariables();
        birthdayCar.getIn();
        System.out.println("miles left: "+birthdayCar.howManyMilesTillOutOfGas());
        System.out.println("max miles: "+birthdayCar.maxMilesPerFillUp());
        System.out.println("\n birthday car v2:");
        birthdayCar.printVariables();
        birthdayCar.getOut();
        System.out.println("\n birthday car v3:");
        birthdayCar.printVariables();
    }
}
