/*
 * This source file was generated by the Gradle 'init' task
 */
package day4;

import static java.lang.System.out;

public class Car {
    int maxSpeed= 100;
    int minSpeed= 0;

    double weight= 4079;

    boolean isTheCarOn= false;
    char condition= 'D';
    String nameOfCar= "Betty";

    double maxFuel = 16;
    double currentFuel = 8;
    double mpg= 26.4;

    int numberOfPeopleInCar = 1;
    int maxNumberOfPeopleInCar= 6;

    public Car() {

    }

    public Car(int customMaxSpeed, double customWeight, double customMaxFuel) {
        maxSpeed= customMaxSpeed;
        weight= customWeight;
        maxFuel= customMaxFuel;
    }

    public int getMaxSpeed() {
        return this.maxSpeed;
    }

    public void setMaxSpeed(int newMaxSpeed) {
        this.maxSpeed = newMaxSpeed;
    }

    public int getMinSpeed() {
        return this.minSpeed;
    }

    public double getWeight() {
        return this.weight;
    }

    boolean isTheCarOn() {
        return this.isTheCarOn;
    }

    public void printVariables() {
        out.println("   max speed: "+ maxSpeed);
        out.println("   min speed: "+ minSpeed);
        out.println("   weight: "+ weight);
        out.println("   is the car on: " +isTheCarOn);
        out.println("   condition: " +condition);
        out.println("   name of car: " +nameOfCar);
        out.println("   max fuel: "+maxFuel);
        out.println("   current fuel: "+currentFuel);
        out.println("   mpg: "+mpg);
        out.println("   number of people in car: "+numberOfPeopleInCar);
    }

    public void washTheCar() {
        condition='A';
    }

    public void upgradeMaxSpeed() {
        setMaxSpeed(getMaxSpeed() + 10);
    }

    public void getIn() {
        if(numberOfPeopleInCar < maxNumberOfPeopleInCar) {
            numberOfPeopleInCar++;
            System.out.println("someone got in the car");
        } else {
            System.out.println("the car is full " + numberOfPeopleInCar + " = " + maxNumberOfPeopleInCar);
        }
    }

    public void getOut() {
        if(numberOfPeopleInCar>0) {
            numberOfPeopleInCar--;
        } else {
            System.out.println("no one is in the car " + numberOfPeopleInCar);
        }
    }

    public double howManyMilesTillOutOfGas() {
        return currentFuel * mpg;
    }

    public double maxMilesPerFillUp() {
        return maxFuel * mpg;
    }

    public void turnTheCarOn() {
        if(!isTheCarOn) {
            isTheCarOn = true;
        } else {
            System.out.println("the car is already on");
        }
    }

    public static void main(String[] args) {
        Car coolCar = new Car();
        coolCar.getOut();
        coolCar.getOut();
        coolCar.getIn();
        coolCar.getIn();
        coolCar.getIn();
        coolCar.getIn();
        coolCar.getIn();
        coolCar.getIn();
        coolCar.getIn();
        coolCar.turnTheCarOn();
        coolCar.turnTheCarOn();
    }
}
