/*
 * This source file was generated by the Gradle 'init' task
 */
package day0;

import static java.lang.System.out;

public class Car {
    int maxSpeed= 100;
    int minSpeed= 0;
    double weight= 4079;
    boolean isTheCarOn= false;
    char condition= 'A';

    public void printVariables() {
        out.println("This is the max speed "+ maxSpeed);
        out.println(minSpeed);
        out.println(weight);
        out.println(isTheCarOn);
        out.println(condition);
    }
    public static void main(String[] args) {
        Car betty= new Car();
        betty.printVariables();
    }
}
