/*
 * This source file was generated by the Gradle 'init' task
 */
package day1;

import static java.lang.System.out;

public class Car {
    int maxSpeed= 100;
    int minSpeed= 0;
    double weight= 4079;
    boolean isTheCarOn= false;
    char condition= 'D';
    String nameOfCar= "Betty";

    public void printVariables() {
        out.println("max speed: "+ maxSpeed);
        out.println("min speed: "+ minSpeed);
        out.println("weight: "+ weight);
        out.println("is the car on: " +isTheCarOn);
        out.println("condition: " +condition);
        out.println("name of car: " +nameOfCar);
    }

    public void washTheCar() {
        condition='A';
    }

    public static void main(String[] args) {
        Car familyCar= new Car();
        System.out.println("family car:");
        familyCar.printVariables();
        Car aliceCar = familyCar;
        familyCar.washTheCar();
        System.out.println("alice's car:");
        aliceCar.printVariables();
        System.out.println("family car:");
        familyCar.printVariables();
    }
}
